export const userInputs = [
  {
    id: "fullName",
    label: "Full Name",
    type: "text",
    placeholder: "John Doe",
  },
  {
    id: "shopOrHospitalName",
    label: "Shop/Hospital Name",
    type: "text",
    placeholder: "XYZ Pharmacy",
  },
  {
    id: "email",
    label: "Email",
    type: "mail",
    placeholder: "john_doe@gmail.com",
  },
  {
    id: "location",
    label: "Address",
    type: "text",
    placeholder: "Elton St. 216 NewYork",
  },
];

export const productInputs = [
  {
    id: "Medicine_Name",
    label: "Medicine Name",
    type: "text",
    placeholder: "Enter Medicine Name",
  },
  {
    id: "Manufacturer",
    label: "Manufacturer",
    type: "text",
    placeholder: "Enter Manufacturer",
  },
  {
    id: "Composition",
    label: "Composition",
    type: "text",
    placeholder: "Enter Composition",
  },
  {
    id: "type",
    label: "Type",
    type: "text",
    placeholder: "Enter Type",
  },
  {
    id: "Information",
    label: "Information",
    type: "text",
    placeholder: "Enter Information",
  },
  {
    id: "Key_Benefits",
    label: "Key Benefits",
    type: "text",
    placeholder: "Enter Key Benefits",
  },
  {
    id: "description",
    label: "Description",
    type: "text",
    placeholder: "Enter Description",
  },
  {
    id: "Directions_for_Use",
    label: "Directions for Use",
    type: "text",
    placeholder: "Enter Directions for Use",
  },
  {
    id: "safety_advise",
    label: "Safety Advice",
    type: "text",
    placeholder: "Enter Safety Advice",
  },
  {
    id: "if_miss",
    label: "If Missed Dose",
    type: "text",
    placeholder: "Enter Instructions for Missed Dose",
  },
  {
    id: "Packaging_Detail",
    label: "Packaging Details",
    type: "text",
    placeholder: "Enter Packaging Details",
  },
  {
    id: "Package",
    label: "Package",
    type: "text",
    placeholder: "Enter Package",
  },
  {
    id: "Qty",
    label: "Quantity",
    type: "text",
    placeholder: "Enter Quantity",
  },
  {
    id: "Product_Form",
    label: "Product Form",
    type: "text",
    placeholder: "Enter Product Form",
  },
  {
    id: "mrp",
    label: "MRP",
    type: "number",
    placeholder: "Enter MRP",
  },
  {
    id: "prescription_required",
    label: "Prescription Required",
    type: "text",
    placeholder: "Yes/No",
  },
  {
    id: "Fact_Box",
    label: "Fact Box",
    type: "text",
    placeholder: "Enter Fact Box Details",
  },
  {
    id: "Uses",
    label: "Uses",
    type: "text",
    placeholder: "Enter Uses",
  },
  {
    id: "storage",
    label: "Storage",
    type: "text",
    placeholder: "Enter Storage Instructions",
  },
  {
    id: "use_of",
    label: "Use Of",
    type: "text",
    placeholder: "Enter Use Of",
  },
  {
    id: "Side_effects",
    label: "Side Effects",
    type: "text",
    placeholder: "Enter Side Effects",
  },
  {
    id: "alcoholInteraction",
    label: "Alcohol Interaction",
    type: "text",
    placeholder: "Enter Alcohol Interaction Details",
  },
  {
    id: "pregnancyInteraction",
    label: "Pregnancy Interaction",
    type: "text",
    placeholder: "Enter Pregnancy Interaction Details",
  },
  {
    id: "lactationInteraction",
    label: "Lactation Interaction",
    type: "text",
    placeholder: "Enter Lactation Interaction Details",
  },
  {
    id: "drivingInteraction",
    label: "Driving Interaction",
    type: "text",
    placeholder: "Enter Driving Interaction Details",
  },
  {
    id: "kidneyInteraction",
    label: "Kidney Interaction",
    type: "text",
    placeholder: "Enter Kidney Interaction Details",
  },
  {
    id: "liverInteraction",
    label: "Liver Interaction",
    type: "text",
    placeholder: "Enter Liver Interaction Details",
  },
  {
    id: "MANUFACTURER_ADDRESS",
    label: "Manufacturer Address",
    type: "text",
    placeholder: "Enter Manufacturer Address",
  },
  {
    id: "Q_A",
    label: "Q&A",
    type: "text",
    placeholder: "Enter Q&A Details",
  },
  {
    id: "How_it_works",
    label: "How It Works",
    type: "text",
    placeholder: "Enter How It Works",
  },
  {
    id: "Interaction",
    label: "Interaction",
    type: "text",
    placeholder: "Enter Interaction Details",
  },
  {
    id: "Manufacturer_details",
    label: "Manufacturer Details",
    type: "text",
    placeholder: "Enter Manufacturer Details",
  },
  {
    id: "Marketer_details",
    label: "Marketer Details",
    type: "text",
    placeholder: "Enter Marketer Details",
  },
  {
    id: "Reference",
    label: "Reference",
    type: "text",
    placeholder: "Enter Reference",
  },
  {
    id: "Expiry_Date",
    label: "Expiry Date",
    type: "date",
    placeholder: "Enter Expiry Date",
  },
  {
    id: "min_quantity",
    label: "Minimum Quantity",
    type: "number",
    placeholder: "Enter Minimum Quantity",
  },
  {
    id: "scheme_quantity",
    label: "Scheme Quantity",
    type: "number",
    placeholder: "Enter Scheme Quantity",
  },
  {
    id: "free_quantity",
    label: "Free Quantity",
    type: "number",
    placeholder: "Enter Free Quantity",
  },
  {
    id: "total_stock",
    label: "Total Stock",
    type: "number",
    placeholder: "Enter Total Stock",
  },
];
